stages:
  - build

variables:
  REGISTRY: "${CI_REGISTRY_IMAGE}"
  IMAGE_TAG: "${CI_COMMIT_REF_SLUG}"
  IMAGE_TAG_LATEST: "latest"

build_multi_arch_manual_main:
  stage: build
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind
      alias: docker
  before_script:
    - echo "Logging into GitLab Container Registry..."
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - echo "Setting up Docker Buildx..."
    - docker context create dind-context
    - docker buildx create --use --name multi-arch-builder dind-context
    - docker buildx inspect --bootstrap

  script:
    - echo "Building and pushing multi-architecture image for linux/amd64 and linux/arm64..."
    - |
      docker buildx build \
        --platform linux/amd64,linux/arm64 \
        --tag "$REGISTRY:$IMAGE_TAG" \
        --tag "$REGISTRY:$IMAGE_TAG_LATEST" \
        --pull \
        --push .

    - echo "Multi-architecture image pushed successfully!"

  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      when: manual
