services:
  app:
    build:
      context: .
    container_name: owlfacerec
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      HOST: "0.0.0.0"
      PORT: "3000"
      RUST_LOG: ${RUST_LOG:-info}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_HOST: ${POSTGRES_HOST:-localhost}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-owlfacerec}

    volumes:
      - ./models:/app/models
