services:
  app:
    build:
      context: .
    container_name: owlfacerec
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      HOST: "0.0.0.0"
      PORT: "3000"
      RUST_LOG: ${RUST_LOG:-info}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_HOST: ${POSTGRES_HOST:-localhost}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-owlfacerec}
      RUSTFACE_MIN_FACE_SIZE: ${RUSTFACE_MIN_FACE_SIZE:-50}
      RUSTFACE_SCORE_THRESH: ${RUSTFACE_SCORE_THRESH:-2.5}
      RUSTFACE_PYRAMID_SCALE_FACTOR: ${RUSTFACE_PYRAMID_SCALE_FACTOR:-0.9}
      RUSTFACE_SLIDE_WINDOW_STEP_X: ${RUSTFACE_SLIDE_WINDOW_STEP_X:-10}
      RUSTFACE_SLIDE_WINDOW_STEP_Y: ${RUSTFACE_SLIDE_WINDOW_STEP_Y:-10}
    volumes:
      - ./models:/app/models

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-owlfacerec}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
